targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          # Add all your modules here
          auto_register: true
          # Include all the modules
          class_name: "GetIt"