name: scalable_ecommerce
description: A scalable Flutter e-commerce application
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.1
  uuid: ^4.5.1
  # Functional Programming
  dartz: ^0.10.1

  # HTTP & Network
  dio: ^5.3.2
  connectivity_plus: ^6.1.4
  pretty_dio_logger: ^1.4.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^10.0.0-beta.4

  # Navigation
  go_router: ^15.2.3

  # Localization
  easy_localization: ^3.0.3

  # UI & Fonts
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.2.0
  photo_view: ^0.15.0
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  # Utils
  equatable: ^2.0.5
  get_it: ^8.0.3
  injectable: ^2.5.0
  logger: ^2.0.2+1
  path_provider: ^2.1.1
  image_picker: ^1.1.2
  # Push Notifications
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.3.0
  permission_handler: ^12.0.0+1
  # Performance
  flutter_hooks: ^0.21.2
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.5.1
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  injectable_generator: 2.6.2

  # Testing
  mockito: ^5.4.2
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/translations/