name: Flutter APK Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  FLUTTER_VERSION: "3.19.0"  # Updated to match your SDK constraints
  DART_VERSION: "3.3.0"      # Explicitly set Dart version

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Set Dart SDK version
        run: flutter downgrade dart:${{ env.DART_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            /opt/hostedtoolcache/flutter
            .pub-cache/
            ${{ github.workspace }}/.dart_tool/
            ${{ github.workspace }}/android/gradle-wrapper/
          key: ${{ runner.os }}-flutter-${{ env.FLUTTER_VERSION }}-dart-${{ env.DART_VERSION }}-${{ hashFiles('pubspec.lock') }}

      - name: Get dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          flutter pub get
          flutter pub cache add flutter_lints@6.0.0

      - name: Run code generators
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 5